
apiVersion: v1
kind: Namespace
metadata:
  name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  namespace: nginx
  labels:
    name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80